# Generated by Django 5.1.3 on 2024-12-12 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_avatar_profile_bio_profile_birth_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="images/avatars/default.jpeg",
                upload_to="images/avatars/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "png", "jpg"]
                    )
                ],
                verbose_name="Аватарка",
            ),
        ),
    ]
